### ISSUE TITLE
zsh:1: command not found: markdown

### ISSUE THREAD

**Issue by lyqscmy** [jrblevin/markdown-mode#11]
Markdown should be installed for Markdown-preview(apt-get install markdown).

**Comment by petere** [comment]
What is the bug here? An Emacs package cannot affect what's installed on the operating system.

**Comment by lyqscmy** [comment]
Sorry,I don't know that.But I think it would be better writen in README.

**Comment by petere** [comment]
It is, under "Customization".

**Comment by lyqscmy** [comment]
Embarras ...Sorry for wasting your time.

2015年8月17日星期一，Peter Eisentraut <notifications@github.com> 写道：

**Comment by Michael-Allan** [comment]
I was embarrassed by the same problem after installing by "Direct Download". Markdown-mode depends on me installing a separate markdown processor on the OS. That makes sense after the fact, of course, but better to know it up front (at least in my case).

**Comment by jrblevin** [comment]
Thanks for following up. Back when I started `markdown-mode`, having Markdown (the Perl script) installed was pretty much the only way to generate HTML and I think most users had it. Now a lot of apps have preview built in, and there are a plethora of Markdown processors, so I think this point deserves to be documented more prominently. I'll fix that.

Since `markdown-mode` does a pretty good job of getting the syntax right in most cases, perhaps one day we can just generate HTML directly from the buffer without an external dependency...
