### ISSUE TITLE
`comment-region` (and `comment-line` in Emacs 25) doesn't work on quoted lines

### ISSUE THREAD

**Issue by cpitclaudel** [jrblevin/markdown-mode#117]
Tested in Emacs 24.5 and 25:

```emacs-lisp
(with-current-buffer (get-buffer-create "*bug*")
  (erase-buffer)
  (markdown-mode)
  (save-excursion (insert "> test\n"))
  (comment-or-uncomment-region (point-at-bol) (point-at-eol))
  (pop-to-buffer (current-buffer)))
```

This goes from 

```
> test
```

to

```
<!-- > test -->
```

(and the syntax highlighting is wrong), then to (repeating `C-x C-;` on that same first line)

```
<!-- <\!-- > test -\-> -->
```

and so on.

Let me know if I can provide more info! Thanks for the cool mode.

**Comment by jrblevin** [comment]
Thanks for reporting this. The inner > was being mistaken for the comment end because a space is allowed in comment closing (i.e., `-- >` *could* be a valid closing, but not in this case because the hyphens are part of the opening). As a result, the syntax table properties were incorrect and hence so was the highlighting and uncomment behavior.

I think it is fixed now, but please reopen if you find otherwise.

**Comment by cpitclaudel** [comment]
Brilliant, thanks!
