### ISSUE TITLE
Following links stopped creating new files

### ISSUE THREAD

**Issue by k-bx** [jrblevin/markdown-mode#120]
Hi! I'm using markdown-mode with emacs's deft.el for quite a long time now for my notes, mostly work-notes, and it has been awesome. And starting from some point in not that long past, one of nice functionalities stopped working.

Previously, I created a link like `[[work/deploy_notes]]`, pressed `C-c C-o` on it, and it created a new note  in a directory `work` by a name `deploy_notes.txt`. Next time I follow that link, it'd open the note instead of creating it, since it exists already.

But some time ago, I did my `cask update` and it seems this does not work anymore. Can you suggest how do I fix this? Thank you!

**Comment by jrblevin** [comment]
Wiki link support is now disabled by default (because checking for missing links adds considerable overhead, and for no benefit for those that don't use wiki links). See the Extensions section of the documentation for details. In short, you'll need to set `markdown-enable-wiki-links` and optionally `markdown-wiki-link-fontify-missing`.

**Comment by k-bx** [comment]
Thank you very much!
