### ISSUE TITLE
These codes are so aggressive

### ISSUE THREAD

**Issue by mola-T** [jrblevin/markdown-mode#127]
```
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode))
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
```

I suggest these part should be left to users.
Personlly, I always use gfm-mode. However, these autoloads alway load later than my .init file, meaning that it takes a higher priority than my `(add-to-list 'auto-mode-alist '("\\.md\\'" . gfm-mode))`.

**Comment by jrblevin** [comment]
I only added the autoloads after repeated requests from users to have them, however, it's not good that you can't override them. I'm now using the append argument of `add-to-list` so that the entries get placed at the end of the list. See commit 57d9daf.

**Comment by raxod502** [comment]
This policy has a disadvantage in Emacs 26. Apparently, some changes were made (I haven't quite determined what), such that now if you visit a file called `CHANGELOG.md`, it opens in ChangeLog mode instead of Markdown mode. Moving the `markdown-mode` entries to the beginning of `auto-mode-alist` fixes the problem.

```elisp
(dolist (regex '("\\.md\\'" "\\.markdown\\'"))
  (setq auto-mode-alist
        (cl-remove regex auto-mode-alist :test #'equal :key #'car))
  (add-to-list 'auto-mode-alist `(,regex . markdown-mode)))
```

I'd also like to note that out of the ~150 packages I use, `markdown-mode` is the only one that adds an entry to the _end_ of `auto-mode-alist`. This is nonstandard behavior. I'd recommend changing it, unless backwards compatibility precludes the possibility, since people like @mola-T can easily override it. (@mola-T mentioned that the autoloads were run later than their init-file, which can be fixed in Emacs ≤26 by running `(package-initialize)` in the init-file, and which doesn't need to be fixed in Emacs ≥27 since autoloads will be evaluated by `package.el` _before_ loading the init-file.)
