### ISSUE TITLE
Indentation doesn't preserve column position

### ISSUE THREAD

**Issue by tom-seddon** [jrblevin/markdown-mode#133]
Despite PR #125, I'm still having problems with indentation not preserving the column position. This happens every time I type a comma.

To reproduce, create a new buffer, enter markdown-mode, type a few chars, and insert a comma - for me, the cursor then moves to the beginning of the line.

I'm using commit  b838d8020445feabd7877ea93ae8d1f2e2e82383.

Thanks,

--Tom

P.S. This isn't a suggested fix by any means, but I had a quick glance at the function, and it looked like it might not always be fixing up the column position. So my workaround for now has been some advice as follows.

```
  (defadvice markdown-indent-line (around markdown-indent-line-around)
    "Fix markdown-indent line."
    (let (column)
      (save-excursion
	(setq column (current-column))
	(back-to-indentation)
	(setq column (- column (current-column)))
	(when (< column 0)
	  (setq column 0)))
      ad-do-it
      (back-to-indentation)
      (move-to-column (+ (current-column) column))))
```

**Comment by jrblevin** [comment]
Thank you for reporting this and being specific about which commit you are using. However, I am unable to reproduce this behavior. Can you please confirm that this still happens when no other minor modes, etc. are loaded that might interfere? In other words, are you launching Emacs with [`emacs -Q`][1]?

[1]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by syohex** [comment]
I cannot reproduce this issue too.

**Comment by tom-seddon** [comment]
This turns out to be a dup of https://github.com/jrblevin/markdown-mode/issues/5 and https://github.com/pierre-arlaud/funda-haxe-mode/issues/11

I've added a note to the Haxe mode issue about a possible fix.

Thanks,

--Tom
