### ISSUE TITLE
Feature request: sub and superscripts

### ISSUE THREAD

**Issue by stevebarratt123** [jrblevin/markdown-mode#134]
In auctex ^superscript^ and ~subscript~ text appears shifted as such in the buffer (in gui). 

It looks awesome and is genuinely really helpful when writing out chemical formulae and other science stuff. It would be really cool if this was possible in markdown-mode too. Markdown has some academic following so I'm sure a number of users would appreciate it.

Thanks for the rad extension anyways

**Comment by syohex** [comment]
This is related to #130.

**Comment by syohex** [comment]
Initial implementation patch is [here](https://gist.github.com/syohex/30b336799510128df8bcf3d387b170b4). Function names are not good because I took most of code from org-mode.

![super-sub-script](https://cloud.githubusercontent.com/assets/554281/14948146/1f6ccbec-1078-11e6-95fe-85cdd7661883.gif)

However we should consider this with #130.

**Comment by jrblevin** [comment]
This is now implemented, along with markup hiding more generally via custom variable `markdown-hide-markup`. This can be toggled interactively using <kbd>C-c C-x C-m</kbd> (`markdown-toggle-markup-hiding`).

See GH-130 for more details on how to toggle, etc.
