### ISSUE TITLE
show language history before complete language list

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#135]
I'm wondering if we can have the `markdown-insert-gfm-code-block` history can be made to show up first followed by the complete language list. Otherwise, the complete language list is so large that it makes it pointless I think to even have the history list if it's at the very bottom. Is there a reason for doing it the way we're doing it now?

**Comment by jrblevin** [comment]
In `markdown-gfm-get-corpus`, the list of used languages (`markdown-gfm-used-languages`) is _prepended_ to the list of known languages (which is what you would like, if I understand correctly). With the default completing-read-function, you can use `M-n` and `M-p` to cycle through previously used languages. The complete language list is used for tab completion.

I must be missing something here. What is your value of the variable `completing-read-function`?

**Comment by blaenk** [comment]
You're absolutely right. I'm not sure how I got mixed up. I added the languages I want to `markdown-gfm-additional-language` too and everything seems to be working great. I'm using helm but yeah, I think I just got mixed up.

**Comment by jrblevin** [comment]
Actually, I think there was something to this. Previously, when a truly new language was used, it was added to the front of the list as returned by `markdown-gfm-get-corpus`. However, when a known language was used it was simply kept in position in the list of recognized languages. This yielded unexpected results with ido, helm, etc. The history was there (e.g., with `M-p`), but that wasn't reflected in the displayed list of language names.

Hopefully this is fixed by this commit: afc5544. Previously used language names (known or unknown) are added to the front of the list. Now, for example, the default choice (in square brackets) should match the name at the front of the list (the most recently used language name).

Thanks for reporting this. Let me know if anything doesn't work as expected after this change.
