### ISSUE TITLE
frontmatter metadata is incorrectly folded

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#136]
So I found out about `markdown-use-pandoc-style-yaml-metadata` which is great. I use outline-minor-mode so that I can fold up all sections for example, but it ends up treating the line right before the end of the metadata block as a header.

![before](http://i.imgur.com/FwbsyAC.png)

![after](http://i.imgur.com/ICwPZkG.png)

**Comment by syohex** [comment]
`outline-minor-mode` uses `outline-on-heading-p` function for finding outline/markdown header. Its implementation is here. It used only regular expression for finding header line so that it mistakes to fold. In your case, the context, whether header line is in YAML header, should be considered for finding header line. Because it looks like outline header line but it is not actually header line.

```lisp
(defun outline-on-heading-p (&optional invisible-ok)
  "Return t if point is on a (visible) heading line.
If INVISIBLE-OK is non-nil, an invisible heading line is ok too."
  (save-excursion
    (beginning-of-line)
    (and (bolp) (or invisible-ok (not (outline-invisible-p)))
	 (looking-at outline-regexp))))
```

We cannot control its behaviour as we expected without overwriting function or advice feature.

**Comment by blaenk** [comment]
How about if we introduce an option to disable Setex headers (the ones underlined)? I only use ATX headers (the ones that go `## Header`), and I always really see people using ATX headers. I'm not saying disable it outright, but since I never use them, I imagine it would help in a situation like this if I could personally disable them on my end.

**Comment by syohex** [comment]
> How about if we introduce an option to disable Setex headers (the ones underlined)?

I disagree. Because it is markdown specification. However you can change it by following configuration.

```lisp
(defun my/markdown-mode-hook ()
  (setq-local outline-regexp "^\\(?:\\(#+\\)[ \t]+\\(.*?\\)[ \t]*\\(#*\\)\\)$"))
(add-hook 'markdown-mode-hook #'my/markdown-mode-hook)
```

**Comment by jrblevin** [comment]
markdown-mode has its own outline visibility cycling (section folding) functions which you should use rather than using `outline-minor-mode` functions directly. You can cycle visibility globally with <kbd>Shift</kbd>+<kbd>Tab</kbd>. Press it multiple times to see more or less.

The new commit (a646fea) adds code to un-hide text in the metadata block that outline-minor-mode mistakenly hides.
