### ISSUE TITLE
Pleas make a stable release

### ISSUE THREAD

**Issue by bremner** [jrblevin/markdown-mode#19]
It's be a few years, and several hundred commits. Lack of stable releases means lack of updates in various places including marmalade, melpa-stable, and linux distros.

**Comment by bremner** [comment]
Oops, bad command line foo. Only 78 commits. Still, please make a stable release every few years ;).

**Comment by jrblevin** [comment]
This has been on my mind too. I'd feel best about a release after some of the list filling issues (e.g., #16) are resolved.

**Comment by AdrieanKhisbe** [comment]
you can also tag `v2.0`: (on tag a3f710de163ec729090ecc13d03e400793fb9e95)

**Comment by jrblevin** [comment]
The 2.0 release happened before I started mirroring the repository on GitHub (but I didn't sync all the tags): http://jblevins.org/git/markdown-mode.git/tag/?id=v2.0

I pushed all of the previous version tags, including [v2.0](https://github.com/jrblevin/markdown-mode/releases/tag/v2.0), to GitHub just now.

Version 2.1 is coming soon. It would be helpful if people can test the current master branch a bit to make sure it's stable.

**Comment by AdrieanKhisbe** [comment]
Do you want I set up test infrastructure with cask and https://github.com/AdrieanKhisbe/cask-package-toolset.el?

**Comment by jrblevin** [comment]
Thanks to @syohex, we already have automated tests set up with [Travis-CI](https://travis-ci.org/jrblevin/markdown-mode). It seems to be working well so far. (What I meant above is real-world testing of things that may not be covered by the test suite.)

**Comment by AdrieanKhisbe** [comment]
Yep I saw. he already did made a good job :)
what I was proposing to add was to adapt ert-runner conventions test, 
setup coverage stats with undercover, and add cucumber tests structure with [ecukes](https://github.com/ecukes/ecukes)

**Comment by jrblevin** [comment]
markdown-mode 2.1 ([release notes](http://jblevins.org/projects/markdown-mode/rev-2-1))

**Comment by jrblevin** [comment]
@AdrieanKhisbe Thanks for generously offering to set these up. After thinking and reading about it quite a bit, I'm pretty content with what we have currently. I like that anyone can clone the repository and run the tests, exactly as I do, without outside dependencies.

If you have thoughts on how to make the existing test framework more transparent, let me know. (With 2.1 released I'll be closing this issue, but feel free to open a new issue or PR.) For example, it might make sense to move the Makefile to the root directory so that the testing process is simply `make test` instead of `make -C tests test` or `cd tests; make test` (the main reason I haven't is that I don't want to break existing workflows).

**Comment by AdrieanKhisbe** [comment]
great for the releases !! :clap: 

-------

With [Cask](http://cask.readthedocs.org/en/latest/), you are set in just a `cask install && make test` :)

What do you mean by *more transparent*?

**Comment by jrblevin** [comment]
> What do you mean by *more transparent*?

More standard, or more easily discoverable by new contributors. I [read][1] that this was one of the main motivations for Cask.

[1]: http://cask.readthedocs.org/en/latest/guide/introduction.html
