### ISSUE TITLE
toggle-markup-hiding stomps on added font-lock-keywords

### ISSUE THREAD

**Issue by hmelman** [jrblevin/markdown-mode#222]
I have the following in my markdown-mode-hook:

```elisp
(font-lock-add-keywords nil '(("\\W@\\w+" . font-lock-variable-name-face))))
```

Works great when I open a file to highlight things like "@CLOSED". However, using `markdown-toggle-markup-hiding` removes this highlighting. I might not mind if it only did this while hiding, but using it again to toggle it off doesn't restore my highlighting.

**Comment by jrblevin** [comment]
Thanks for pointing this out. Currently `markdown-mode` re-defines `font-lock-keywords` directly when toggling some settings (like math mode), which is why your addition to the list is lost. A better approach would be for `markdown-mode` to add and remove the feature-specific elements individually, without modifying the other elements. After I get v2.3 out (I'm waiting a bit in case there are outstanding bugs), I'll work on this for the next version.

In the meantime, possible workarounds are to add your highlighter to `markdown-mode-font-lock-keywords-basic` instead, which shouldn't be modified after toggling markup, or to advise `markdown-reload-extensions` and use `font-lock-add-keywords` as in your hook above.

**Comment by jrblevin** [comment]
Hopefully this is fixed now, but let me know if you still have issues adding keywords.

**Comment by hmelman** [comment]
Given the keywords in my original comment, I'm still having the same problem. Am I supposed to be using something else?

**Comment by hmelman** [comment]
You're right that setting it that way works. I've changed my markdown-mode customization hooks :)

**Comment by jrblevin** [comment]
Glad you were able to adjust your configuration. It appears to be fixed now when adding buffer-specific keywords as well.
