### ISSUE TITLE
Issue on Termux (Android)

### ISSUE THREAD

**Issue by SparkyCola** [jrblevin/markdown-mode#237]
When I try to generate html, i get the following message in the body:
`/data/data/com.termux/files/usr/bin/sh: 1: markdown: not found`
I don't get what this is supposed to mean or where it comes from, just that shell seems to have interpreted something as a "markdown" command. Do you have any idea, it's probably just a missing dependency.

**Comment by jrblevin** [comment]
`markdown-mode` expects that the executable for the Markdown processor of your choice can be found in the Emacs `exec-path`. By default it looks for `markdown`.

Install a Markdown processor (if you don't have one already) and set `markdown-command` to be the full path of the executable on your system.

See also #150.

**Comment by jrblevin** [comment]
Sorry, I closed accidentally but I hopefully this clears things up. There is indeed a dependency on a command to convert Markdown to HTML (although I'm not sure how to install it on Termux).

**Comment by SparkyCola** [comment]
I could just download the source and compile it (Termux has gcc, make and more stuff), however I fortunately discovered Org which seems to be better for my use. Thanks for you fast help anyway.

**Comment by excalamus** [comment]
This issue seems related to #426.  

My understanding is this: `markdown-mode` uses the `markdown-command` to call a markdown parser/renderer.  Many people use `pandoc`. However, `pandoc` is [unavailable on termux](https://github.com/termux/termux-packages/issues/372).  Termux does have [`hoedown`](https://github.com/hoedown/hoedown).  After installing `hoedown` (via `pkg install hoedown`) calling `(setq markdown-command "hoedown")` will set `markdown-mode` to use that renderer.
