### ISSUE TITLE
creating a list from the region

### ISSUE THREAD

**Issue by coldpour** [jrblevin/markdown-mode#239]
is there a way to create an unordered list from the lines selected by the region in your package already? I'm thinking in terms of a WYSIWYG editor where you select a few lines and then click the "bullet" button. 

I've written a custom function in my init file to do it, but I was wondering if either your package already had this feature and i just hadn't found it yet, or perhaps you wouldn't mind adding this to your package.

```elisp
  (defun coldpour/markdown-bullet (beg end)
    (interactive "r")
    (let ((indent (current-column)))
      (goto-char beg)
      (beginning-of-line)
      (while (and (not (looking-at "[ \t]*$"))
                  (<= (point) end))
        (insert "* ")
        (setq end (+ end 2))
        (forward-line))))
```

so the following:

```markdown
one
two
three
```

when all three lines are marked by the region, and `M-x coldpour/markdown-bullet` would turn into:

```markdown
* one
* two
* three
```

**Comment by jrblevin** [comment]
There's nothing like this currently. I'd be happy to take a look at a pull request. It would be ideal if it could be added to the existing list item insertion command. In other words, when there is an active region, use your command. Otherwise, keep the current behavior. You can use `(if (markdown-use-region-p) ...` to determine whether the region should be used. Also, the hard-coded "* " marker should be changed to use `markdown-unordered-list-item-prefix` for generality. Of course, then the hard-coded 2 should be changed as well. You can use a marker instead of an integer variable, then you won't have to do the math by hand.

**Comment by dchenbecker** [comment]
For something like this, I usually just use `string-rectangle` to insert the bullets or numbers on each line.

**Comment by syohex** [comment]
I suppose it is enough to use `string-rectangle`(`Ctrl-x r t`) as above said and `C-u rectangle-number-lines` (`Ctrl-x r N`)for this purpose. Sample screencast is here.

![rectangle](https://user-images.githubusercontent.com/554281/83519989-e69b7500-a517-11ea-8f1d-5c57ab191b3f.gif)
