### ISSUE TITLE
Please consider changing the "new list item" hotkey

### ISSUE THREAD

**Issue by philsf** [jrblevin/markdown-mode#26]
Rationale: Emacs uses `C-c C-j` to create new items in some list environments, most notably `LaTeX` related modes. AFAIK, `C-j` is used for indentation in some programming modes, but I'm not used to using it.

Do you have any strong feelings for using this particular combo for this particular funcion? Would it be possible to use `C-c C-j` to create new list items instead? It would be easier users of content modes to use the same hotkeys for the same purposes in content-oriented modes. 

BTW, I'm fairly new to markdown and GFM, and just found out about your emacs mode. Your docs accelerated my markdown learning. Kudos for both the code and the docs! Thanks!

**Comment by jrblevin** [comment]
Thanks for this suggestion. Actually, I picked <kbd>M-RET</kbd> originally because that's what I use in AUCTeX for inserting items. Now I see that it is an alias for <kbd>C-c C-j</kbd>. I see the logic in using <kbd>C-c C-j</kbd> for new list items, but the problem is that in `markdown-mode` <kbd>C-c C-j</kbd> is used for jumping in various contexts (footnote markers and definitions, reference links and definitions, etc.). We'd have to find a better keybinding for that--suggestions?

**Comment by philsf** [comment]
@jrblevin I think "jumping" would be rather well represented by the often common "next" and "previous" hotkeys.

I suppose you already use `C-n` and `C-p` for another purpose? What about `C-c C-n` and `C-c C-p`?

**Comment by philsf** [comment]
I hope this request doesn't disrupt the workflow of your current users. I'm just a newcomer with a wishlist ;-)

**Comment by jrblevin** [comment]
I've been thinking again about a possible new keybinding for `markdown-jump` (currently `C-c C-j`). Here are some free ones under `C-c C-?`:

* `C-c C-r` (for <em>r</em>eturn)
* `C-c C-v` (for <em>v</em>isit)
* `C-c C-l` (any good mnemonic here?)
* `C-c C-d` (any good mnemonic here?)

Another option: Emacs uses both `M-j` and `C-M-j` for `comment-indent-new-line`. Perhaps we could override `C-M-j` (for <em>j</em>ump)?  Does anyone use `C-M-j` for this instead of `M-j`?

**Comment by philsf** [comment]
* `C-c C-l`
How about Loop? I think it's more in tune with the semantics than the ones above. Does the feature actually loop, after reaching the last section? 

My suggestion is: does latex-mode or AucTex have a similar feature, to jump between sections? If so, you could use the same keybinding as well.

**Comment by jrblevin** [comment]
Thanks for the mnemonic suggestion. I thought about AUCTeX, etc., but I couldn't think of any similar behavior. I should say this command doesn't jump between sections, rather, between reference link or footnote markers in text and their definitions below. For example, it will jump back and forth between line 1 and 3 for the reference link below.

```
[link][1]

[1]: http://github.com/
```

**Comment by philsf** [comment]
Sorry for that, I just confirmed the bejavior in the docs after commenting. But since it does go back and forth, "loop" would be an usable mnenomic, right?

**Comment by jrblevin** [comment]
Sure. Now that I think about it, with <kbd>C-c C-d</kbd> we have <em>d</em>efinition, jumping between the link/footnote and the definition.

**Comment by jrblevin** [comment]
OK, here you go: 3bf565b. I do think <kbd>C-c C-j</kbd> is good for inserting list items, since there is clear precedence for it. I moved `markdown-jump` to <kbd>C-c C-l</kbd>. The other nice thing about that one is that it's adjacent to <kbd>C-c C-o</kbd> which can be used to follow/browse/open reference links (as opposed to visiting their definitions). Sorry it took me several months to finally decide on an alternative keybinding!
