### ISSUE TITLE
Adding support for rendering atx headers in the margin

### ISSUE THREAD

**Issue by algal** [jrblevin/markdown-mode#272]
I'd like to add a new custom variable, `markdown-marginalize-header`, which will cause opening atx-style headers to be rendered into the left margin of the window. Together with a font face on headers, this creates a nice clean visual style where you can see the header levels without the header syntax marks cluttering up the text.

You can see it partly working, and partly broken, here:

<img width="672" alt="marginalheaderwip" src="https://user-images.githubusercontent.com/264412/31595757-c03cca82-b1f2-11e7-833a-9b2adb61b276.png">

I would love any help or advice on how to make this work. I've never worked with window margins before, and I don't think I understand the re-parse and re-display cycle, so I'm not sure where the change should go.

The emacs documentation on rendering into the display margins is at https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Margins.html

My work on this is at:  https://github.com/algal/markdown-mode/tree/feature/marginal-headers

**Comment by jrblevin** [comment]
This is great! Thanks for working on this. I once thought something like this would be nice, but I didn't know how to do it or if it was possible.

Markdown Mode processes the buffer in two-passes: 1) syntax-propertization, where the overall syntax is parsed and marked with text properties, and 2) fontification, where font lock properties are applied. As such, this code might be better placed in `markdown-fontify-headings`. In that function, the `display` property is already set when markup-hiding is enabled.  You might be able to add another condition for heading marginalization, to set `markup-props` accordingly.

Another thought: since markdown only defines six levels of headings, can we just fix the margin width to 6 (or 7, if we need a space), set the `(margin left-margin)` value, and avoid the `copy-string` function? I haven't had a chance to run the code yet, so I might be missing something here.

**Comment by algal** [comment]
Hi! Thanks for the guidance. That does indeed sound like a better place to put the new logic that sets the display properties. I’ll give it a try and see how it goes.

The `copy-string` function is there because I thought it would be simpler to use the actual header markup string to build the string that’s placed in the window margin, since then the window margin string will naturally use the same header mark character as the real header. But if we generate the window margin string, then we have to predefined the character or else take extra care to generate the same char as that line of that document is using. But maybe this is too cute, or there are risks or performance penalties associated with `copy-string`?

Yeah, 6 or 7 characters sounds like a good default. I’ll put that in.

**Comment by algal** [comment]
Based on your pointers, I was able to implement it.

I think what I've got is correct. I hope it fits with your plan. I'll put the details in a pull request and close this issue:

https://github.com/jrblevin/markdown-mode/pull/274
