### ISSUE TITLE
test-markdown-filling/no-break-before-list-item succeeds in Emacs 26

### ISSUE THREAD

**Issue by phst** [jrblevin/markdown-mode#279]
## Expected Behavior

Test test-markdown-filling/no-break-before-list-item fails because it's expected to fail.

## Actual Behavior

Test succeeds.

## Steps to Reproduce

make test EMACS=/path/to/emacs26

## Backtrace

```
Ran 368 tests, 367 results as expected, 1 unexpected (2017-10-31 00:44:10+0100)
2 expected failures

1 unexpected results:
   PASSED  test-markdown-filling/no-break-before-list-item

make[1]: *** [test] Error 1
```

## Software Versions

Emacs repo version ee493663ba6571a5cb47c51e68aae679d94ee1f0
Markdown repo version 736cb7e7af3f34bbea83c5396ed79ce07e7b820a
OS: Ubuntu 14.04

**Comment by jrblevin** [comment]
Tests in the test suite that are marked as expected to fail are ones that aren't fixed yet for some reason (i.e., known to be broken).  This one was due to odd filling behavior in Emacs, so this is good news and means it has been fixed in Emacs 26.  I'll work on making it pass conditional on the Emacs version.
