### ISSUE TITLE
markdown-next-paragraph chokes on certain tables

### ISSUE THREAD

**Issue by justinabrahms** [jrblevin/markdown-mode#29]
I have a table with a large blank first cell and `markdown-next-paragraph` (as well as previous) seems to choke on it. `C-g` stops and I can manually go over it.

version 2.0

Table:

```
|                   | Percentage | Amount (@ 75k) |
|-------------------|:----------:|---------------:|
| Everything Else   |19%         | $14,250        |

```

**Comment by jrblevin** [comment]
Thanks for this report and sorry for the delay. Once I got around to testing this I can't reproduce the behavior you mentioned. It has been a long time since v2.0 (and I am working towards a new stable release), but perhaps the issue was fixed since then? If you do indeed find that this issue is present in the latest development version, please reopen and provide a specific test case for me to check.
