### ISSUE TITLE
markdown-toggle-inline-images does nothing

### ISSUE THREAD

**Issue by vividbytes** [jrblevin/markdown-mode#323]
markdown-toggle-inline-images and markdown-display-inline-images don't appear to do anything. Is there a way to debug this issue, I'm not seeing any error messages.

If I open the image emacs displays it correctly. Inline images in org-mode work fine as well.

Sorry if this is a stupid question. I'm fairly new to emacs.

**Comment by jrblevin** [comment]
I'm not sure what org-mode does, but markdown-mode requires Emacs to be built with imagemagick support. What happens if you eval this (with <kbd>M-:</kbd> for instance)?

```
(image-type-available-p 'imagemagick)
```

If that's not the issue, then you could use the debugger to inspect `markdown-display-inline-images` as it runs. For example, with `debug-on-entry` or `edebug-on-entry`.

**Comment by asok** [comment]
@vividbytes maybe the confusion is that only images on the local fs are displayed, not remote ones. That was at least in my case.

**Comment by syohex** [comment]
```lisp
(setq markdown-display-remote-images t)
```

I cannot reproduce this issue both local and remote image. If you want to display remote image, please add above configuration to your init.el

![toggle-image](https://user-images.githubusercontent.com/554281/83410356-35320c00-a451-11ea-9866-00fadc2b03ff.gif)
