### ISSUE TITLE
Unexpected Strikethrough Behavior

### ISSUE THREAD

**Issue by alyms108** [jrblevin/markdown-mode#362]
## Expected Behavior

Pressing `C-c C-s s` applies strikethrough formatting to the word under the cursor.
## Actual Behavior
When only the markdown-mode package is loaded, `C-c C-s s` behaves as expected. When I have other packages loaded, the keybind applies bold formatting instead. When I check to see what function the key combination is bound to, it says it's bound to `markdown-insert-strike-through` when only markdown-mode is loaded, and bound to `markdown-insert-bold` when I have all my packages loaded. In fact, the strikethrough function seems to disappear altogether when I have all packages loaded. The bindings for several other functions also seem to change when I have all packages loaded, and I can't tell if there's a conflict between markdown-mode and the other packages or if there's something else going on.

## Software Versions

- Markdown Mode: version 2.3
- Emacs: 24.5.1
- OS: Linux Mint 18.3

**Comment by jrblevin** [comment]
Thanks for this report. Unfortunately, I don't think there is anything I can do without knowing which other package is needed to reproduce the behavior you're seeing.

It sounds like something is manipulating the keymaps, but it's strange that it's still reporting the correct function. What happens when you call `markdown-insert-strike-through` directly using `M-x`?

**Comment by alyms108** [comment]
Sorry about that. The additional packages I'm loading are evil, org-mode, and tabbar, and I installed the  emacs-goodies-el package via `sudo apt install` (this package is where tabbar comes from). When I try to call `markdown-insert-strike-through` via `M-x`, `[no match]` shows in the minibuffer. It's as if the command no longer exists. Everything works as it should when only the markdown-mode package is loaded.

**Comment by jrblevin** [comment]
Since you don't have that many packages, can you individually disable them to see which one is the culprit (my money is on evil)? Once you find it, check your config for that package to see if there is anything relevant. Otherwise, there may be some built-in adverse interaction between the packages.

**Comment by alyms108** [comment]
I did some looking around at what was included in the `emacs-goodies-el` package, and it looks like markdown-mode is included in it, along with a lot of other emacs packages. It's possible there was some conflict there, so I currently have it removed. With just org-mode, evil and markdown-mode itself installed, there aren't any conflicts and strikethrough shows up like it should.

**Comment by syohex** [comment]
I cannot reproduce this issue with installing `emacs-googies-el` and loading `evil`, `org-mode`, `tabbar-mode` packages.
