### ISSUE TITLE
Make a release 2.4

### ISSUE THREAD

**Issue by frankgerhardt** [jrblevin/markdown-mode#385]
After 5 min trying out markdown-mode I ran into bug #334. There is a commit fixing it but no release since 2017. Old: #19.

Please make a release 2.4 with the latest stable code.

**Comment by sten0** [comment]
Hi @jrblevin, we've had f3c54e34cc5228001af36a5301883325319f21d4 in Debian since early/mid September 2019 with upwards of 2000 confirmed users, and no bug reports, so I think it's safe to tag  e9dff50 as `v2.4`.

**Comment by sten0** [comment]
Hi @jrblevin and @syohex, master has had 231 commits since v2.3, and it feels like we're past due for a release.  In addition to the many bugfixes, I feel like users will appreciate fa3deb4405f07527252a5030106f4f03a232d09e.

Are there any blockers for a release?  The only one that jumped out at me was maybe #406.  It doesn't need to be perfect, just an improvement over v2.3 :-)  P.S. That's why Debian has been tracking master for so long, even though there is a lot of cultural pressure to prefer stable versions...but at this point, it feels like it's been too long since the last release (eg: ~20months).

Even a v2.4beta release would be appreciated!

**Comment by syohex** [comment]
> Are there any blockers for a release?

I'm not sure. I have fixed #406 today. I would like to drop older Emacs versions if version is bumped #450

**Comment by sten0** [comment]
> > Are there any blockers for a release?
> 
> I'm not sure. I have fixed #406 today. I would like to drop older Emacs versions if version is bumped #450

Thank you for #406 :-)  I agree 100% with your rationale at #450.  Let's do a release, and if necessary, follow up with a 2.4.1 in a month.

**Comment by syohex** [comment]
markdown-mode is modified a lot recently. So I wait 2 weeks or 1 month for reporting issues. I'll tag version if there is no big issue.

**Comment by sten0** [comment]
@syohex, sounds good :-)  I've rebased the Debian package onto f47a2e9 to help with the testing and stabilisation effort.

**Comment by sten0** [comment]
@syohex  It looks like we're on track for that end of May release ;-)  Thanks again for all of your work.  I believe that it has resulted in the doubling of markdown-mode's users ([*Debian popcon*](https://qa.debian.org/cgi-bin/popcon-png?packages=elpa-markdown-mode&show_installed=1&show_vote=0&show_old=0&show_recent=0&show_nofiles=0&want_percent=0&want_legend=1&want_ticks=1&from_date=&to_date=&hlght_date=&date_fmt=%25Y-%25m)).  FYI, the troughs are sampling errors, and popcon is kind of like bogomips, except that it preselects for an opt-in volunteer subset of Debian/Ubuntu/Mint/Pop!OS/etc. users.  In this case exclusively a subset of Debian users.  Total users are at at minimum 4x higher, I think.

Anyways, 'just wanted to share the good news, thank you, and confirm the plan for an end of May release :-)

**Comment by syohex** [comment]
We have tagged v2.4.
