### ISSUE TITLE
Indenting a new line goes three spaces, instead of respecting "tab-width"

### ISSUE THREAD

**Issue by doomchild** [jrblevin/markdown-mode#388]
After thinking that this was a bug in `editorconfig-mode` (and based on the help I got from them at https://github.com/editorconfig/editorconfig-emacs/issues/194), it appears that `markdown-mode` is ignoring `tab-width` when indenting a new line.  It just statically goes three spaces, even if `tab-width` is set to `4`.  A second `<Tab>` moves it one space further to the correct point, and further indentations appear to correctly go `4` spaces.

## Expected Behavior

Starting with this file (~/test.md) and `tab-width` set to `4`:

```markdown
# Thing

1. Something
```

Pressing `<Enter>` once puts the cursor here (the pipe is the cursor):

```markdown
# Thing

1. Something
|
```

Pressing `<Tab>` to indent the cursor should move the cursor `4` spaces:

```markdown
# Thing

1. Something
    |
```

## Actual Behavior

Starting with this file (~/test.md) and `tab-width` set to `4`:

```markdown
# Thing

1. Something
```

Pressing `<Enter>` once puts the cursor here (the pipe is the cursor):

```markdown
# Thing

1. Something
|
```

Pressing `<Tab>` to indent the cursor actually moves the cursor `3` spaces:

```markdown
# Thing

1. Something
   |
```

A second `<Tab>` press is required to indent the missing space.

## Steps to Reproduce

1. Set `tab-width` to `4`.
2. Open a file called `test.md`.
3. Enter the text "1. Something".
4. Press `<Enter>`.
5. Press '<Tab>`.
6. Notice that the cursor has only moved `3` spaces.

## Software Versions

- Markdown Mode: 2.4-dev
- Emacs: GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.6.0, NS appkit-1561.40 Version 10.13.5 (Build 17F77)) of 2018-06-27
- OS: macOS Mojave (10.14.3)

**Comment by syohex** [comment]
Indent of markdown-mode works like `indent-relative` function which is used in text-mode. It does not work as you expect. markdown-mode can custom indent function via `markdown-indent-function` variable. If you want to indent as you expect, please write function and set it.

**Comment by doomchild** [comment]
That seems really backwards.  I thought Markdown _required_ 4 spaces.  Certainly some rendering tools do (Stash, in particular, gets REALLY confused if you don't use a width of 4).  Wouldn't it make more sense for `markdown-mode` to do the standard thing and provide a hook for non-standard scenarios?

**Comment by jrblevin** [comment]
It's not the case that the tab width is fixed at three spaces in `markdown-mode`. That would be a strange choice, I agree. It sets `tab-width` to 4, since that is the natural choice for Markdown. However, there is also a list of possible intended indentation positions that is context-specific and includes the fixed tab-width position. Pressing tab cycles through those likely positions in buffer-order, left to right.

For example, you get three spaces instead of four in the scenario above because of the ordered list on the previous line. It's possible you would like to indent three spaces for hanging indentation of the ordered list, or perhaps you want to create a nested code block by indenting eight spaces in this case.

Relative indentation is not specific to `markdown-mode` by the way, but is common in text-based modes (as opposed to programming modes). Try the same steps as above in `text-mode` and the same thing happens.

If you do still prefer "tab key == insert four spaces", then as @syohex suggested to you can change `markdown-indent-function`. I think `indent-tab` is the function you would want to get a fixed-`tab-width` tab key.

**Comment by doomchild** [comment]
Okay, that makes a lot more sense.  Thanks for the extra context.
