### ISSUE TITLE
"multimarkdown failed with exit code 127"

### ISSUE THREAD

**Issue by tree-fiddy** [jrblevin/markdown-mode#426]
## Expected Behavior
C-c C-c [p,o,e...etc.] should render the markdown file.  But it does not and instead throws the error mentioned in the title.

I am expecting a preview window, PDF, html file... or anything really, with the markdown rendered properly.

## Actual Behavior
Error: user-error: multimarkdown failed with exit code 127

## Steps to Reproduce

1. Open an arbitrary .md file in emacs (emacsmacport)
2. Issue command: C-c C-c and tried to preview, open, export.

## Backtrace
user-error: multimarkdown failed with exit code 127

## Software Versions
markdown-mode version 2.4-dev
GNU Emacs 26.3 build 1
OS: macOS Catalina

**Comment by tonight-halfmoon** [comment]
Install markdown rendering engine/implementation/converter
`brew install markdown`
But this won't help if, for example, you'd like to see your tables are rendered in html view, and some other stuff.
`brew install pandoc`
and customise `markdown-command` in your emacs's init file
`(setq markdown-command "pandoc --from markdown --to html --standalone"`

**Comment by kirk86** [comment]
@tonight-halfmoon Thanks for the tip, if you don't mind I have a similar question. What happens if we don't really want to generate an output file. For instance, if I just want live editing and viewing the rendered markdown side by side on another buffer? Is this possible?

I've seen in the docs that we'll have to configure and install another third party app? Is there any other alternative without installing other third party apps?

**Comment by tonight-halfmoon** [comment]
@kirk86 
My pleasure. I haven't tried it... but perhaps this is what you are looking for: [flymd](https://github.com/mola-T/flymd)

**Comment by syohex** [comment]
Please set your markdown converter to `markdown-command` as below. If you want to use `multimarkdown` command, then please install it and set PATH.

```lisp
(setq markdown-command "pandoc")
```
