### ISSUE TITLE
Markdown mode breaks Emacs

### ISSUE THREAD

**Issue by novakboskov** [jrblevin/markdown-mode#48]
markdown-mode 20151224.808
GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8) of 2015-12-30.
It totally breaks and exit Emacs when typing text in markdown-mode. When I switch major mode to text-mode everything is fine. It is easy to reproduce this, but because it exits Emacs I can't provide any useful information; hence,
- open .md file
- type few characters and try to save changes
- Emacs quits without any messages.

**Comment by jrblevin** [comment]
Thanks for your report. Interestingly, I've been running GNU Emacs 25.1.50.1 from 2015-12-09 with no issue. When I get a build of 25.1.50.2, I will try to reproduce this. In the meantime, can you provide some additional details?

* Can you confirm the issue is still present with `emacs -Q`?
* When you say it quits, does it quit gracefully or crash? I presume the latter.
* Can you try `M-x toggle-debug-on-error' before saving?

**Comment by novakboskov** [comment]
I have upgraded Emacs earlier today, before upgrade it was worked for me too.
- Whith ```emacs -Q``` there is no markdown-mode and ```.md``` files are in ```Fundamental mode``` so it works well, no exit.
- I think it crashes since it doesn't show "Are you sure ..." message, but OS (Ubuntu 14.04) doesn't show any crash report, which usually does.
- ```M-x toggle-debug-on-error``` have no effect, everything is same, it just exits and do not enter in any error message or stacktrace.

Now I noticed that it crashes only with files which contain html code, e.g. it crashes with:
```
<div class="bs-callout bs-callout-danger">

### Database Configuration is Required

If you haven't already, then please follow the steps below to configure your database connection and run the necessary migrations.

* Run `lein run migrate` in the root of the project to create the tables.
* Restart the application.

</div>


### Managing Your Middleware

Request middleware functions are located under the `guestbook.middleware` namespace.

This namespace is reserved for any custom middleware for the application. Some default middleware is
already defined here. The middleware is assembled in the `wrap-base` function.

Middleware used for development is placed in the `guestbook.dev-middleware` namespace found in
the `env/dev/clj/` source path.

### Here are some links to get started

1. [HTML templating](http://www.luminusweb.net/docs/html_templating.md)
2. [Accessing the database](http://www.luminusweb.net/docs/database.md)
3. [Setting response types](http://www.luminusweb.net/docs/responses.md)
4. [Defining routes](http://www.luminusweb.net/docs/routes.md)
5. [Adding middleware](http://www.luminusweb.net/docs/middleware.md)
6. [Sessions and cookies](http://www.luminusweb.net/docs/sessions_cookies.md)
7. [Security](http://www.luminusweb.net/docs/security.md)
8. [Deploying the application](http://www.luminusweb.net/docs/deployment.md)
```
and it' works when I delete html code.

**Comment by jrblevin** [comment]
Thanks for these details and the test case. That will be helpful. With `emacs -Q`, I meant to then also load `markdown-mode.el` manually with `load-file` and `M-x markdown-mode`. This will isolate the issue from any other local configuration.

**Comment by novakboskov** [comment]
Oh... it looks like everything is fine when I enter emacs with ```emacs -Q```, load file and then activate markdown-mode. Seems like bug lays somewhere in Prelude, I'll investigate it in a few days.
Sorry for the noise.
Thank you for your work and happy holidays! :)

**Comment by jrblevin** [comment]
No problem. Thanks again for the report.

**Comment by jmarca** [comment]
Hitting a similar bug here today.

converted HTML to markdown using pandoc, then I was going through and stripping html bits (divs, etc) that survived the pandoc step, and it keeps crashing.  

Like the original poster, I'm not running markdown-mode all by itself, so it could be an interaction issue.

It seems to happen when I end up with unbalanced angle brackets `>`, for example, when global search and replace `<div id="` with something else.  If I can get a clean test case I'll post it, but until I can be certain the culprit is markdown I'm not going to open a new issue.
