### ISSUE TITLE
Brackets order is wrong

### ISSUE THREAD

**Issue by kyrylo** [jrblevin/markdown-mode#5]
![output](https://cloud.githubusercontent.com/assets/1079123/8849872/c2ed44de-314b-11e5-95da-13d92e56425a.gif)

Please note that I tried disabling autopair, but the bug remained. This is critical for me. I have to use Sublime now :(

**Comment by jrblevin** [comment]
Markdown Mode does not insert paired delimiters, so I cannot replicate what you are seeing. This must be a result of something else in your local configuration. If it is an adverse interaction with another package that could be fixed by changing Markdown Mode somehow, then I am open to that, but you'll need to provide more information to help identify the source of the problem (at least Markdown Mode version and the name of other library and/or description of the configuration that causes the problem).

**Comment by jrblevin** [comment]
To follow up, I tried using `electric-pair-mode` and when doing so brackets of all kinds typed in markdown-mode were inserted in the correct order. You mentioned `autopair`, not `electric-pair-mode`, but I didn't try installing that since you said that you had disabled it, and if so it shouldn't be the issue.

**Comment by kyrylo** [comment]
Hi, @jrblevin! Thanks for the reply. Here's my configuration: https://github.com/kyrylo/dot/tree/master/cfg/emacs.d

I use Cask and ELPA. Do you have any clues what might cause this (I'm not an ELisp pro)? This issue happens only with `markdown-mode`.

![output](https://cloud.githubusercontent.com/assets/1079123/8852959/ea40433c-3160-11e5-9dd9-3d01f2b6c5ae.gif)

**Comment by jrblevin** [comment]
I suspect this has something to do with autopair and if so you may want to file a bug report with that package. Curly braces, for example, are not special in Markdown and Markdown Mode does not treat them as special, so there is no reason typing a curly brace should make the point move.

From your configuration it seems that autopair is enabled globally. Please try loading markdown-mode without your local other configuration (or at the very least comment out the autopair stuff). In other words, don't let autopair load first and then disable it, but load markdown-mode without it.

**Comment by kyrylo** [comment]
Thanks for the information!

It turns out the culprit was [`funda-haxe-mode`](https://github.com/pierre-arlaud/funda-haxe-mode/issues/11). When I [deleted](https://github.com/kyrylo/dot/commit/d4ff9c9ea984526ca5069f0eaedf0cbf2d567cf9) it, markdown-mode started working fine.

Thanks!
