### ISSUE TITLE
Text link with spaces inside it

### ISSUE THREAD

**Issue by unoqualsiasi60** [jrblevin/markdown-mode#509]
## Expected Behavior

I press  `C-c C-l` to insert e link. The Text link must cointain spaces
When a digit a space I cannot insert link text with spaces inside. I get a "No match" advice.

 

## Actual Behavior

When I type in a space in the _Text link_ field  I get the message "No match" and  I'm not allowed to proceed.

 

In other words: the `[text](URL)` generated by `C-c C-l`cannot be composed by spaces inside the text itself and I must correct the text after the C-c C-l command.

But If I insert the text from a region I can keep every spaces inside the text selected but non add other spaces.

## Steps to Reproduce

1. Step A `C-c C-l`
2. Step B Insert URL
3. Step C Insert Text link with some spaces inside it

## Software Versions

- Markdown Mode: markdown-mode-20200622.20
- Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2019-12-03
- OS: Linux Ubuntu 20.4 LTS, Linux Fedora 32

**Comment by syohex** [comment]
Please use `Ctrl-q space` or set `minibuffer-local-completion-map` configuration as below. This behavior is `completing-read` specification.

```lisp
(defun my/markdown-mode-hook ()
  (define-key minibuffer-local-completion-map (kbd "SPC") 'self-insert-command))
```

**Comment by unoqualsiasi60** [comment]
Thanks! it works
Franco Pasut

Il giorno sab 4 lug 2020 alle ore 17:38 Shohei YOSHIDA <
notifications@github.com> ha scritto:

**Comment by YoungFrog** [comment]
Would you consider re-opening this issue? I was about to open a new one, but then I realized there are already 3 of them (#537, #546 and this one). All are closed atm.

I think this behaviour is annoying because the "Link text" is always free text for me. I always write spaces in there.

I definitely don't want to hit `C-q` before every space.
I don't want to change my `minibuffer-local-completion-map` because it has a global effect
Another workaround, which would solve the problem for me, is overwriting the whole function (`markdown--insert-link-or-image`) in my `.emacs` in order to get rid of the `completing-read`.

I'm thinking out loud: 
1. imho we should **at least** document the behaviour and possible workarounds in the docstring of `markdown-insert-[link,image]`
1. another easy step would be to add a user option to change the behaviour (e.g. define `markdown-read-text-link-with-completion` would default to `t`) but maybe this would add unwanted complexity to an already pretty complex function.
1. instead is there a way to distinguish between when `completing-read` is actually useful (maybe when the `uri-or-ref` part is empty?) and the cases where it's probably unwanted ? Maybe we can then have two different commands : one which has the completing-read behaviour, another one which doesn't have it.

Unfortunately I don't know/use markdown enough, and I don't know when it is useful to have completion for the link text.

**Comment by syohex** [comment]
> I don't want to change my `minibuffer-local-completion-map` because it has a global effect

How about this ?

```lisp
(defun my/markdown-mode-hook ()
  (define-key minibuffer-local-completion-map (kbd "SPC")
    (lambda ()
      (interactive)
      (if (with-current-buffer (window-buffer (minibuffer-selected-window))
            (eq major-mode 'markdown-mode))
          (insert " ")
        (minibuffer-complete-word)))))

(add-hook 'markdown-mode-hook 'my/markdown-mode-hook)
```

**Comment by YoungFrog** [comment]
Indeed, that's probably a better workaround. Thanks for taking the time to write it.

I still believe that 4 bug reports on the same problem warrants a more thorough response (i.e. within markdown-mode itself), but I won't insist any further.
