### ISSUE TITLE
Markdown documents don't have syntax colouring anymore

### ISSUE THREAD

**Issue by drivet** [jrblevin/markdown-mode#6]
Hi,

I upgraded markdown-mode via elpa to markdown-mode-20150724.2116 recently and now I'm not getting any syntax colouring.  Other things seems to work fine.

Any idea what may have changed recently?  Was it in the general area of syntax colouring?

Thanks in advance for any help.

**Comment by jrblevin** [comment]
There have been no *major* changes to syntax highlighting. I added a variable that lets one customize the internal "support mode" used to optimize syntax highlighting. The default is the same as the Emacs default, so I don't think that should be an issue. I also made some changes to how `markdown-mode` behaves when it reads file-local variables. It has been working fine for me, but it's possible something is going wrong there. Can you please do the following:

1. Confirm that `markdown-mode` is indeed loading? You should see "Markdown" in the mode line. I only ask because there were some autoload changes since the last release.

2. Do you happen to see see any errors in `*Messages*` when `markdown-mode` loads?

3. Load Emacs without any local configuration (e.g., using the `--no-init-file` argument). Then create a new file without an extension (e.g., `README`) and manually invoke `M-x markdown-mode`? The idea here is that we can bypass anything else that might be interfering and focus on the initial mode loading in isolation.

**Comment by drivet** [comment]
Here's what I did:

1. I moved my .emacs.d/init.el file out of way and restarted emacs.  When I start emacs with a --no--init-file, for some reason it can't see markdown-mode
1. I created a README file in my home directory, loaded it in emacs, and ran M-x markdown-mode
1. I do indeed see a Markdown indicator in the mode line, and I'm able to, for example, bold a piece of selected text from the menu choice.
1. BUT I see no syntax colouring for emphasized text, or links

The *Messages* buffer looks okay:

Loading 00debian-vars...done
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...done
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Error while loading 50dictionaries-common: Symbol's value as variable is void: debian-aspell-only-dictionary-alist
Loading /etc/emacs/site-start.d/50pylint.el (source)...
Loading pylint...done
Loading /etc/emacs/site-start.d/50pylint.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Making completion list...
Quit
Undo!

**Comment by jrblevin** [comment]
Thanks for these details. I was able to replicate this myself now and I will look into it more when I can. If you run `M-x markdown-reload-extensions` manually in the meantime I think it will enable syntax highlighting for you.

I think this is due to commit 8300a05. Sometimes `markdown-reload-extensions`, which sets up the font lock keywords for syntax coloring, was being called twice. I wanted to avoid this, but now it seems that in some cases it isn't being called at all.

**Comment by drivet** [comment]
Running `M-x markdown-reload-extensions` does bring back the syntax colouring, thanks!

**Comment by jrblevin** [comment]
I think I have fixed this in commit 86fb0ea. Please give it a try at your convenience and let me know if it fixes the issue.

**Comment by ronalde** [comment]
I'm having the same issue (no syntax highlighting / coloring) with current cf1ed9f1d828b0065da7df129fbedf599cdba5d7 on arch running emacs  24.5.1.

Furthermore the `M-x markdown-reload-extensions` does not change anything. 

Also tried starting emacs ith `--no-init-file`, manually loading the library `M-x load-library ~/.emacs.d/elisp/markdown-mode/markdown-mode.el`, and starting markdown-mode with `M-x markdown-mode`. For the rest the mode works as expected.

No messages at startup.

Regards,
Ronald

**Comment by jrblevin** [comment]
Thanks for your detailed report. I reverted the offending commit while I look for a better approach (related to [this issue](https://github.com/defunkt/markdown-mode/pull/3)).

**Comment by ronalde** [comment]
Thanks for your swift reaction: my issue is fixed!
