### ISSUE TITLE
Sponsoring this project?

### ISSUE THREAD

**Issue by mhucka** [jrblevin/markdown-mode#707]
Markdown-mode is fantastic, and I think I'm not the only person who would be willing to sponsor it via GitHub's sponsorship facility. Would you consider adding a GitHub "Sponsor" button to this project?

**Comment by syohex** [comment]
Thanks but no thanks, we appreciate your kindness. I'm a main maintainer of this project. I don't have the project permission and I can't add the sponsorship button.

And I think it is difficult to share money between original author and current maintainers if the button is added, because we live in different countries and sending money to different countries among individuals is complicated due to each countries laws
