### ISSUE TITLE
option to use lowercase language name in gfm blocks

### ISSUE THREAD

**Issue by blaenk** [jrblevin/markdown-mode#71]
First of all, woah!! Thanks a lot @cosmicexplorer for your great work on #54!

It looks and seems to work beautifully! I had been following what seemed to me like a convention which was to use the lowercase representation of language names. The implementation of #54 seems to use the capitalized language, e.g. `JavaScript` or `Python` versus `javascript` or `python`. I know it's such a minor gripe! But I was wondering if you could possibly add an option to perhaps `(downcase chosen-candidate)` before inserting it?

I already have many codeblocks that use the lowercase names (which I really prefer) and everyone else I've seen does the same thing, so I'm not too eager to break with that convention and have mixed styles.

**Comment by blaenk** [comment]
I just saw #59 but I admit I'm not sure I understand it. I noticed of course that I could "add" my own language, so for example if I type `python` and create a new one, it will indeed enter `python`, but now I'll have `python` _and_ `Python` even though I only intend to have one. I think an option like I'm saying would be nice because users who want this wouldn't have to create "alternate" versions of each language they use and get a lot of leftover capitalized languages in the completing-read list.

To be clear, I of course don't mind (and in fact appreciate) the fact that the names are capitalized in the completing-read list, what I'm saying is that I would prefer it if the chosen language was inserted as a lower-case version of it.

**Comment by cosmicexplorer** [comment]
#73 adds a defcustom `markdown-gfm-downcase-languages`, which adds the behavior you describe and defaults to `t`. The weird thing I've noticed is that using helm, even with `completion-ignore-case` off, `completing-read` will return `""` if the entered pattern is a downcased version of a completion candidate, which shouldn't happen. I believe this is a bug in helm's `completing-read`, since `completing-read-default` seems to work just fine; I will investigate this.

Essentially, it now defaults to using the lowercased version of a language for all of the "preloaded" languages. If it parses a buffer upon opening and finds languages that are not preloaded (this includes alternative capitalizations), it adds those as candidates. This means that within a file, if that file uses the uppercased versions of "Ruby" or "Python", for example, those will be included as completions, but only within that buffer. Otherwise, the lowercased versions of all languages will be preferred for completion of a partial input. I've added this behavior to the test case for this feature.

**Comment by blaenk** [comment]
Amazing! I really appreciate it, thank you!

**Comment by cosmicexplorer** [comment]
https://github.com/emacs-helm/helm/issues/1331 I've made an issue on helm, so that's definitely a helm thing. Should be fine for everyone else.

**Comment by jrblevin** [comment]
Good idea. I also use lowercase names (in my workflows they usually translate to class names for XHTML elements), so I appreciate having this flexibility.
