### ISSUE TITLE
Symbols in table

### ISSUE THREAD

**Issue by bommbo** [jrblevin/markdown-mode#723]
## Expected Behavior

| a | a_b | c |
|---|-----|---|
| a | a_b | c |

## Actual Behavior
<img width="97" alt="image" src="https://user-images.githubusercontent.com/61496351/180898009-22ec3238-bb34-4bdd-b48a-e322c3aa1b63.png">

## Software Versions

- Markdown Mode: v2.5
- Emacs: GNU Emacs 28.1
- OS: archlinux

**Comment by syohex** [comment]
Please use `gfm-mode` instead of `markdown-mode`. I suppose that gfm-mode fontifies as you expect. [Original markdown specification](https://daringfireball.net/projects/markdown/syntax) does not say anything about your case.

See also
- https://github.com/jrblevin/markdown-mode/issues/671#issuecomment-988463154
