### ISSUE TITLE
configurable fontification of identifiers_with_underscores, etc.

### ISSUE THREAD

**Issue by seabadger** [jrblevin/markdown-mode#749]
Underscore characters ('_') that occurs inside a word-like string (e.g. foo_bar, foo_bar_baz) is being interpreted as markup, and fontified accordingly. From what I've read, there's no 'standard' behavior for this, i.e. different implementations make different choices. Making this configurable would allow a given user to use their preferred behavior.

## Expected Behavior
Underscore characters in the middle of a word treated as literal underscores (i.e., as if '\_' was used).

## Actual Behavior 
A line like
   foo_bar some words baz_bam
gets rendered with italicized text between underscores 

## Steps to Reproduce
Type the line 
   foo_bar some words baz_bam
into a markdown buffer.

## Backtrace
N/A

## Software Versions

- Markdown Mode: 2.6-alpha
- Emacs: 28.2
- OS: macOS Monterey 12.6.3

**Comment by syohex** [comment]
https://github.com/jrblevin/markdown-mode/issues/448#issuecomment-615576026

Please see the above comment. `markdown-mode` implements original markdown specification and it says you need to escape underscores in such case. So you need to write like `foo\_bar some words baz\_bam` or use `gfm-mode` instead of `markdown-mode`.
