### ISSUE TITLE
MELPA: Link to this GitHub repo

### ISSUE THREAD

**Issue by mcandre** [jrblevin/markdown-mode#84]
Please have the MELPA package link to this GitHub repo to make it easier to find.

**Comment by syohex** [comment]
Is this MELPA recipe issue ? (el-get uses this repository directly)
github repository information is in Commentary section(https://melpa.org/#/markdown-mode).

**Comment by jrblevin** [comment]
I don't understand. The MELPA page is generated automatically, so how does one link to a Git repository from MELPA other than in the commentary?

**Comment by vyp** [comment]
@jrblevin I think if the recipe (https://github.com/melpa/melpa/blob/master/recipes/markdown-mode) uses the github fetcher, the Melpa webpage automatically has a "Homepage" button next to the "Recipe" and "Download" buttons. I assume this is what @mcandre is referring to. (I suppose this should be the same for other fetchers like Gitlab.) I guess the reason it doesn't do this for the git fetcher is because you obviously cannot browse a git url in the browser. I'm not sure about this though, so I'll cc @purcell to clarify. (hope you don't mind)

**Comment by purcell** [comment]
Indeed. If someone would like to file a PR which updates the MELPA recipe to use this github repo, then we'll automatically link here from the package page on our website.

**Comment by jrblevin** [comment]
Thanks for clarifying, everyone, and thanks to @vyp for the MELPA pull request.

**Comment by syohex** [comment]
The PR has been merged. Now markdown-mode MELPA recipe uses this github repository.
